In [1]:
market2 <- read.table('../reg2020/market-2.txt', header=T)

In [2]:
t(market2)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
ID 1.0   2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0 10.0  11.0  12.0  13.0  14.0 
X1 4.2   8.5  9.3  7.5  6.3 12.2  6.5 10.4  5.8  9.2   7.2   8.5  10.6  13.9 
X2 4.5  12.0 15.0  8.5  7.4 18.5  5.5 16.5  3.7 13.5   5.2  15.0  14.4  13.3 
Y  9.3  18.5 22.8 17.7 14.6 27.9 12.5 25.2 10.8 20.5  14.9  19.2  22.5  28.4 
   [,15]
ID 15.0 
X1 12.7 
X2 12.5 
Y  25.6

In [4]:
X <- market2[,c(2,3)]
t(X)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
X1 4.2   8.5  9.3 7.5  6.3  12.2 6.5  10.4 5.8   9.2  7.2    8.5  10.6  13.9 
X2 4.5  12.0 15.0 8.5  7.4  18.5 5.5  16.5 3.7  13.5  5.2   15.0  14.4  13.3 
   [,15]
X1 12.7 
X2 12.5

In [5]:
X <- cbind(1,X)
t(X)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
1  1.0   1.0  1.0 1.0  1.0   1.0 1.0   1.0 1.0   1.0  1.0    1.0   1.0   1.0 
X1 4.2   8.5  9.3 7.5  6.3  12.2 6.5  10.4 5.8   9.2  7.2    8.5  10.6  13.9 
X2 4.5  12.0 15.0 8.5  7.4  18.5 5.5  16.5 3.7  13.5  5.2   15.0  14.4  13.3 
   [,15]
1   1.0 
X1 12.7 
X2 12.5

In [6]:
Y <- market2[,4]
t(Y)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 9.3  18.5 22.8 17.7 14.6 27.9 12.5 25.2 10.8 20.5  14.9  19.2  22.5  28.4 
     [,15]
[1,] 25.6

In [7]:
X <- as.matrix(X)
t(X)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
1  1.0   1.0  1.0 1.0  1.0   1.0 1.0   1.0 1.0   1.0  1.0    1.0   1.0   1.0 
X1 4.2   8.5  9.3 7.5  6.3  12.2 6.5  10.4 5.8   9.2  7.2    8.5  10.6  13.9 
X2 4.5  12.0 15.0 8.5  7.4  18.5 5.5  16.5 3.7  13.5  5.2   15.0  14.4  13.3 
   [,15]
1   1.0 
X1 12.7 
X2 12.5

In [8]:
Y <- as.matrix(Y)
t(Y)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 9.3  18.5 22.8 17.7 14.6 27.9 12.5 25.2 10.8 20.5  14.9  19.2  22.5  28.4 
     [,15]
[1,] 25.6

In [9]:
XTX <- t(X) %*% X
XTX

1     X1      X2     
1   15.0  132.80  165.50
X1 132.8 1280.80 1610.68
X2 165.5 1610.68 2149.49

In [10]:
XTXI <- solve(XTX)
XTXI

1           X1          X2          
1   0.82483283 -0.09810472  0.010004922
X1 -0.09810472  0.02520628 -0.011334282
X2  0.01000492 -0.01133428  0.008188029

In [11]:
XTY <- t(X) %*% Y
XTY

[,1]   
1   290.40
X1 2796.89
X2 3568.95

In [12]:
beta <- XTXI %*% XTY
beta

[,1]     
1  0.8504051
X1 1.5581063
X2 0.4273559

In [13]:
beta <- round(beta, 3)
beta

[,1] 
1  0.850
X1 1.558
X2 0.427