In [2]:
market2 <- read.table('../reg2020/market-2.txt', header=T)

In [3]:
t(market2)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
ID 1.0   2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0 10.0  11.0  12.0  13.0  14.0 
X1 4.2   8.5  9.3  7.5  6.3 12.2  6.5 10.4  5.8  9.2   7.2   8.5  10.6  13.9 
X2 4.5  12.0 15.0  8.5  7.4 18.5  5.5 16.5  3.7 13.5   5.2  15.0  14.4  13.3 
Y  9.3  18.5 22.8 17.7 14.6 27.9 12.5 25.2 10.8 20.5  14.9  19.2  22.5  28.4 
   [,15]
ID 15.0 
X1 12.7 
X2 12.5 
Y  25.6

In [4]:
X <- market2[,c(2,3)]
t(X)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
X1 4.2   8.5  9.3 7.5  6.3  12.2 6.5  10.4 5.8   9.2  7.2    8.5  10.6  13.9 
X2 4.5  12.0 15.0 8.5  7.4  18.5 5.5  16.5 3.7  13.5  5.2   15.0  14.4  13.3 
   [,15]
X1 12.7 
X2 12.5

In [5]:
X <- cbind(1,X)
t(X)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
1  1.0   1.0  1.0 1.0  1.0   1.0 1.0   1.0 1.0   1.0  1.0    1.0   1.0   1.0 
X1 4.2   8.5  9.3 7.5  6.3  12.2 6.5  10.4 5.8   9.2  7.2    8.5  10.6  13.9 
X2 4.5  12.0 15.0 8.5  7.4  18.5 5.5  16.5 3.7  13.5  5.2   15.0  14.4  13.3 
   [,15]
1   1.0 
X1 12.7 
X2 12.5

In [6]:
Y <- market2[,4]
t(Y)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 9.3  18.5 22.8 17.7 14.6 27.9 12.5 25.2 10.8 20.5  14.9  19.2  22.5  28.4 
     [,15]
[1,] 25.6

In [7]:
X <- as.matrix(X)
t(X)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
1  1.0   1.0  1.0 1.0  1.0   1.0 1.0   1.0 1.0   1.0  1.0    1.0   1.0   1.0 
X1 4.2   8.5  9.3 7.5  6.3  12.2 6.5  10.4 5.8   9.2  7.2    8.5  10.6  13.9 
X2 4.5  12.0 15.0 8.5  7.4  18.5 5.5  16.5 3.7  13.5  5.2   15.0  14.4  13.3 
   [,15]
1   1.0 
X1 12.7 
X2 12.5

In [8]:
Y <- as.matrix(Y)
t(Y)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 9.3  18.5 22.8 17.7 14.6 27.9 12.5 25.2 10.8 20.5  14.9  19.2  22.5  28.4 
     [,15]
[1,] 25.6

In [9]:
XTX <- t(X) %*% X
XTX

1     X1      X2     
1   15.0  132.80  165.50
X1 132.8 1280.80 1610.68
X2 165.5 1610.68 2149.49

In [10]:
XTXI <- solve(XTX)
XTXI

1           X1          X2          
1   0.82483283 -0.09810472  0.010004922
X1 -0.09810472  0.02520628 -0.011334282
X2  0.01000492 -0.01133428  0.008188029

In [11]:
XTY <- t(X) %*% Y
XTY

[,1]   
1   290.40
X1 2796.89
X2 3568.95

In [12]:
beta <- XTXI %*% XTY
beta

[,1]     
1  0.8504051
X1 1.5581063
X2 0.4273559

In [13]:
beta <- round(beta, 3)
beta

[,1] 
1  0.850
X1 1.558
X2 0.427

In [15]:
H <- X %*% solve(t(X) %*% X)  %*% t(X)
H

[,1]         [,2]         [,3]         [,4]        [,5]       
 [1,]  0.272808044  0.081217885  0.044365012 0.127095743  0.17981509
 [2,]  0.081217885  0.085207364  0.105076834 0.063350496  0.07407387
 [3,]  0.044365012  0.105076834  0.160366034 0.042819467  0.05310189
 [4,]  0.127095743  0.063350496  0.042819467 0.087663295  0.10008642
 [5,]  0.179815086  0.074073865  0.053101892 0.100086423  0.12879161
 [6,] -0.083673784  0.089194585  0.158592426 0.008248588 -0.01695042
 [7,]  0.172597136  0.047453565 -0.005729631 0.109274121  0.12569416
 [8,] -0.004331244  0.101107683  0.164420275 0.028774660  0.02639073
 [9,]  0.204222231  0.039901675 -0.031489038 0.122780516  0.14337668
[10,]  0.049818669  0.089183291  0.122611280 0.051465284  0.05663423
[11,]  0.142553196  0.029973717 -0.037544951 0.107116012  0.10971188
[12,]  0.078959091  0.120966988  0.187326444 0.047138659  0.07164495
[13,] -0.011398608  0.072103407  0.100105445 0.039043148  0.02345521
[14,] -0.153270959 -0.006555343 -0.041264438 0.027170822 -0.05214430
[15,] -0.100777496  0.007743989 -0.022757052 0.037972766 -0.02368200
      [,6]         [,7]         [,8]         [,9]         [,10]      
 [1,] -0.083673784  0.172597136 -0.004331244  0.204222231 0.049818669
 [2,]  0.089194585  0.047453565  0.101107683  0.039901675 0.089183291
 [3,]  0.158592426 -0.005729631  0.164420275 -0.031489038 0.122611280
 [4,]  0.008248588  0.109274121  0.028774660  0.122780516 0.051465284
 [5,] -0.016950424  0.125694160  0.026390731  0.143376685 0.056634233
 [6,]  0.239021098 -0.061094799  0.193100754 -0.102673603 0.123811822
 [7,] -0.061094799  0.161777802 -0.029942928  0.192940253 0.021881239
 [8,]  0.193100754 -0.029942928  0.179994055 -0.062875978 0.125871472
 [9,] -0.102673603  0.192940253 -0.062875978  0.234420608 0.006052783
[10,]  0.123811822  0.021881239  0.125871472  0.006052783 0.100131370
[11,] -0.068246959  0.169746229 -0.054194705  0.204880133 0.003547060
[12,]  0.158810247 -0.008447689  0.182800294 -0.036412944 0.137987054
[13,]  0.144315334  0.009867465  0.118214223 -0.008224768 0.087864894
[14,]  0.117891080  0.041576582  0.012442688  0.040068370 0.006545112
[15,]  0.099653635  0.052406495  0.018228020  0.053033077 0.016594437
      [,11]       [,12]        [,13]        [,14]        [,15]       
 [1,]  0.14255320  0.078959091 -0.011398608 -0.153270959 -0.100777496
 [2,]  0.02997372  0.120966988  0.072103407 -0.006555343  0.007743989
 [3,] -0.03754495  0.187326444  0.100105445 -0.041264438 -0.022757052
 [4,]  0.10711601  0.047138659  0.039043148  0.027170822  0.037972766
 [5,]  0.10971188  0.071644948  0.023455209 -0.052144295 -0.023681999
 [6,] -0.06824696  0.158810247  0.144315334  0.117891080  0.099653635
 [7,]  0.16974623 -0.008447689  0.009867465  0.041576582  0.052406495
 [8,] -0.05419471  0.182800294  0.118214223  0.012442688  0.018228020
 [9,]  0.20488013 -0.036412944 -0.008224768  0.040068370  0.053033077
[10,]  0.00354706  0.137987054  0.087864894  0.006545112  0.016594437
[11,]  0.19556306 -0.057098756  0.011644477  0.124230498  0.118119116
[12,] -0.05709876  0.230418877  0.095410864 -0.122477778 -0.087026300
[13,]  0.01164448  0.095410864  0.103072648  0.113891727  0.100634534
[14,]  0.12423050 -0.122477778  0.113891727  0.491401648  0.400494287
[15,]  0.11811912 -0.087026300  0.100634534  0.400494287  0.329362492

In [16]:
HD <- H %*% H
HD

[,1]         [,2]         [,3]         [,4]        [,5]       
 [1,]  0.272808044  0.081217885  0.044365012 0.127095743  0.17981509
 [2,]  0.081217885  0.085207364  0.105076834 0.063350496  0.07407387
 [3,]  0.044365012  0.105076834  0.160366034 0.042819467  0.05310189
 [4,]  0.127095743  0.063350496  0.042819467 0.087663295  0.10008642
 [5,]  0.179815086  0.074073865  0.053101892 0.100086423  0.12879161
 [6,] -0.083673784  0.089194585  0.158592426 0.008248588 -0.01695042
 [7,]  0.172597136  0.047453565 -0.005729631 0.109274121  0.12569416
 [8,] -0.004331244  0.101107683  0.164420275 0.028774660  0.02639073
 [9,]  0.204222231  0.039901675 -0.031489038 0.122780516  0.14337668
[10,]  0.049818669  0.089183291  0.122611280 0.051465284  0.05663423
[11,]  0.142553196  0.029973717 -0.037544951 0.107116012  0.10971188
[12,]  0.078959091  0.120966988  0.187326444 0.047138659  0.07164495
[13,] -0.011398608  0.072103407  0.100105445 0.039043148  0.02345521
[14,] -0.153270959 -0.006555343 -0.041264438 0.027170822 -0.05214430
[15,] -0.100777496  0.007743989 -0.022757052 0.037972766 -0.02368200
      [,6]         [,7]         [,8]         [,9]         [,10]      
 [1,] -0.083673784  0.172597136 -0.004331244  0.204222231 0.049818669
 [2,]  0.089194585  0.047453565  0.101107683  0.039901675 0.089183291
 [3,]  0.158592426 -0.005729631  0.164420275 -0.031489038 0.122611280
 [4,]  0.008248588  0.109274121  0.028774660  0.122780516 0.051465284
 [5,] -0.016950424  0.125694160  0.026390731  0.143376685 0.056634233
 [6,]  0.239021098 -0.061094799  0.193100754 -0.102673603 0.123811822
 [7,] -0.061094799  0.161777802 -0.029942928  0.192940253 0.021881239
 [8,]  0.193100754 -0.029942928  0.179994055 -0.062875978 0.125871472
 [9,] -0.102673603  0.192940253 -0.062875978  0.234420608 0.006052783
[10,]  0.123811822  0.021881239  0.125871472  0.006052783 0.100131370
[11,] -0.068246959  0.169746229 -0.054194705  0.204880133 0.003547060
[12,]  0.158810247 -0.008447689  0.182800294 -0.036412944 0.137987054
[13,]  0.144315334  0.009867465  0.118214223 -0.008224768 0.087864894
[14,]  0.117891080  0.041576582  0.012442688  0.040068370 0.006545112
[15,]  0.099653635  0.052406495  0.018228020  0.053033077 0.016594437
      [,11]       [,12]        [,13]        [,14]        [,15]       
 [1,]  0.14255320  0.078959091 -0.011398608 -0.153270959 -0.100777496
 [2,]  0.02997372  0.120966988  0.072103407 -0.006555343  0.007743989
 [3,] -0.03754495  0.187326444  0.100105445 -0.041264438 -0.022757052
 [4,]  0.10711601  0.047138659  0.039043148  0.027170822  0.037972766
 [5,]  0.10971188  0.071644948  0.023455209 -0.052144295 -0.023681999
 [6,] -0.06824696  0.158810247  0.144315334  0.117891080  0.099653635
 [7,]  0.16974623 -0.008447689  0.009867465  0.041576582  0.052406495
 [8,] -0.05419471  0.182800294  0.118214223  0.012442688  0.018228020
 [9,]  0.20488013 -0.036412944 -0.008224768  0.040068370  0.053033077
[10,]  0.00354706  0.137987054  0.087864894  0.006545112  0.016594437
[11,]  0.19556306 -0.057098756  0.011644477  0.124230498  0.118119116
[12,] -0.05709876  0.230418877  0.095410864 -0.122477778 -0.087026300
[13,]  0.01164448  0.095410864  0.103072648  0.113891727  0.100634534
[14,]  0.12423050 -0.122477778  0.113891727  0.491401648  0.400494287
[15,]  0.11811912 -0.087026300  0.100634534  0.400494287  0.329362492

In [28]:
t(H)

[,1]         [,2]         [,3]         [,4]        [,5]       
 [1,]  0.272808044  0.081217885  0.044365012 0.127095743  0.17981509
 [2,]  0.081217885  0.085207364  0.105076834 0.063350496  0.07407387
 [3,]  0.044365012  0.105076834  0.160366034 0.042819467  0.05310189
 [4,]  0.127095743  0.063350496  0.042819467 0.087663295  0.10008642
 [5,]  0.179815086  0.074073865  0.053101892 0.100086423  0.12879161
 [6,] -0.083673784  0.089194585  0.158592426 0.008248588 -0.01695042
 [7,]  0.172597136  0.047453565 -0.005729631 0.109274121  0.12569416
 [8,] -0.004331244  0.101107683  0.164420275 0.028774660  0.02639073
 [9,]  0.204222231  0.039901675 -0.031489038 0.122780516  0.14337668
[10,]  0.049818669  0.089183291  0.122611280 0.051465284  0.05663423
[11,]  0.142553196  0.029973717 -0.037544951 0.107116012  0.10971188
[12,]  0.078959091  0.120966988  0.187326444 0.047138659  0.07164495
[13,] -0.011398608  0.072103407  0.100105445 0.039043148  0.02345521
[14,] -0.153270959 -0.006555343 -0.041264438 0.027170822 -0.05214430
[15,] -0.100777496  0.007743989 -0.022757052 0.037972766 -0.02368200
      [,6]         [,7]         [,8]         [,9]         [,10]      
 [1,] -0.083673784  0.172597136 -0.004331244  0.204222231 0.049818669
 [2,]  0.089194585  0.047453565  0.101107683  0.039901675 0.089183291
 [3,]  0.158592426 -0.005729631  0.164420275 -0.031489038 0.122611280
 [4,]  0.008248588  0.109274121  0.028774660  0.122780516 0.051465284
 [5,] -0.016950424  0.125694160  0.026390731  0.143376685 0.056634233
 [6,]  0.239021098 -0.061094799  0.193100754 -0.102673603 0.123811822
 [7,] -0.061094799  0.161777802 -0.029942928  0.192940253 0.021881239
 [8,]  0.193100754 -0.029942928  0.179994055 -0.062875978 0.125871472
 [9,] -0.102673603  0.192940253 -0.062875978  0.234420608 0.006052783
[10,]  0.123811822  0.021881239  0.125871472  0.006052783 0.100131370
[11,] -0.068246959  0.169746229 -0.054194705  0.204880133 0.003547060
[12,]  0.158810247 -0.008447689  0.182800294 -0.036412944 0.137987054
[13,]  0.144315334  0.009867465  0.118214223 -0.008224768 0.087864894
[14,]  0.117891080  0.041576582  0.012442688  0.040068370 0.006545112
[15,]  0.099653635  0.052406495  0.018228020  0.053033077 0.016594437
      [,11]       [,12]        [,13]        [,14]        [,15]       
 [1,]  0.14255320  0.078959091 -0.011398608 -0.153270959 -0.100777496
 [2,]  0.02997372  0.120966988  0.072103407 -0.006555343  0.007743989
 [3,] -0.03754495  0.187326444  0.100105445 -0.041264438 -0.022757052
 [4,]  0.10711601  0.047138659  0.039043148  0.027170822  0.037972766
 [5,]  0.10971188  0.071644948  0.023455209 -0.052144295 -0.023681999
 [6,] -0.06824696  0.158810247  0.144315334  0.117891080  0.099653635
 [7,]  0.16974623 -0.008447689  0.009867465  0.041576582  0.052406495
 [8,] -0.05419471  0.182800294  0.118214223  0.012442688  0.018228020
 [9,]  0.20488013 -0.036412944 -0.008224768  0.040068370  0.053033077
[10,]  0.00354706  0.137987054  0.087864894  0.006545112  0.016594437
[11,]  0.19556306 -0.057098756  0.011644477  0.124230498  0.118119116
[12,] -0.05709876  0.230418877  0.095410864 -0.122477778 -0.087026300
[13,]  0.01164448  0.095410864  0.103072648  0.113891727  0.100634534
[14,]  0.12423050 -0.122477778  0.113891727  0.491401648  0.400494287
[15,]  0.11811912 -0.087026300  0.100634534  0.400494287  0.329362492